version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
  whatsapp-bot:
    build: ./whatsapp-bot
    ports:
      - "5002:5002"
    env_file: .env
  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    env_file: .env 